@startuml
       User -> UserHomePage: Views Recipe List
       User -> UserHomePage: Clicks Checkbox to add a recipe to favorites
       UserHomePage -> System: Request Add Recipe to Favorites

       System -> System: Finds recipe by ID
       System -> System: Adds Recipe to Favorite List

       System --> FavoriteList: Return Recipe Favorites List
       User -> FavoriteList: Views Recipe Favorites List

       @enduml